const express = require("express");
const router = express.Router();
const payrollController = require("../controllers/payrollController");
const requireAuth = require("../middleware/authMiddleware");
const requireAdmin = require("../middleware/adminMiddleware");
router.post("/", requireAuth, requireAdmin, payrollController.createPayroll);
router.get("/mine", requireAuth, payrollController.getMyPayrolls);
router.get("/", requireAuth, requireAdmin, payrollController.getAllPayrolls);
router.patch("/:id", requireAuth, requireAdmin, payrollController.updatePayroll);
module.exports = router;
